
services:
  # 1. Python-Backend
  server:
    build: ./server
    platform: linux/amd64
    volumes:
      - ./server:/server
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - backend-net

  # 2. React-Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    volumes:
      - ./client:/client
      - /client/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - backend-net

  # 3. MongoDB-Datenbank
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-net

volumes:
  mongo_data:

networks:
  backend-net:
    driver: bridge
